[phases.setup]
nixPkgs = ["python310", "git"]

[phases.install]
cmds = [
  "python -m venv .venv && source .venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
